name: Nightly Build

on:
    schedule:
    -   cron: '0 0 * * *'  # Run every day at midnight

jobs:

    tests:

        if: github.repository == 'sponce24/aiida-abinit'  # Prevent running the builds on forks as well

        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10']

        services:
            postgres:
                image: postgres:12
            rabbitmq:
                image: rabbitmq:latest
                ports:
                -   5672:5672

        steps:
        -   uses: actions/checkout@v2

        -   name: Cache python dependencies
            id: cache-pip
            uses: actions/cache@v1
            with:
                path: ~/.cache/pip
                key: pip-${{ matrix.python-version }}-tests-${{ hashFiles('**/setup.json') }}
                restore-keys:
                    pip-${{ matrix.python-version }}-tests

        -   name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v2
            with:
                python-version: ${{ matrix.python-version }}

        -   name: Install python dependencies
            continue-on-error: true
            id: install
            run: |
                pip install --upgrade setuptools
                pip install git+https://github.com/aiidateam/aiida-core@develop#egg=aiida-core[atomic_tools]
                pip install -e .[tests]
                reentry scan

        -   name: Run pytest
            continue-on-error: true
            id: tests
            run:
                pytest -sv tests
